debian/tests/common-functions: detect when running inside GH actions
Skip the debootstrap based tests inside Gh actions, the `mknod`
command fails there so the tests are not useful.

Also enable `set -ex`

diff --git a/debian/tests/common-functions b/debian/tests/common-functions
--- a/debian/tests/common-functions
+++ b/debian/tests/common-functions
@@ -30,6 +30,11 @@ do_debootstrap() {
     chroot_dir="$2"
     mirror="$3"
 
+    if [ "$GITHUB_ACTIONS" = "true" ]; then
+       echo "mkdnod fails in GH actions, skipping debootstrap"
+       exit 77
+    fi
+
     ret=0
     for i in $(seq 5); do
         debootstrap --include eatmydata,time "$@" 2>&1 && break || ret=$?
